modLoader = "kotlinforforge"
loaderVersion = "[$kotlinForForgeVersion,)"
#issueTrackerURL = ""
license = "MIT"

[[mods]]
modId = "$id"
version = "$version"
displayName = "$name"
authors = "vini2003"
description = '''
Because bamboo needs some more uses.
'''
#logoFile = ""

[[dependencies.$id]]
modId = "forge"
mandatory = true
versionRange = "[$forgeVersion,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.$id]]
modId = "minecraft"
mandatory = true
versionRange = "[$minecraftVersion,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.$id]]
modId = "architectury"
mandatory = true
versionRange = "[$architecturyVersion,)"
ordering = "AFTER"
side = "BOTH"